# https://github.com/rust-lang/rustfmt
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

indent_style = "Block"
use_small_heuristics = "Off"
combine_control_expr = false
wrap_comments = true
error_on_line_overflow = false
error_on_unformatted = true
## fn_args_layout = "Compressed"
# # Warning: Unknown configuration option `fn_args_density`
# fn_args_density = "Compressed"
# brace_style = "PreferSameLine"
# where_single_line = true
format_strings = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
merge_imports = true
match_block_trailing_comma = true
normalize_comments = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
report_todo = "Unnumbered"
report_fixme = "Unnumbered"
# struct_field_align_threshold = 80
struct_field_align_threshold = 32
struct_lit_single_line = false
trailing_comma = "Vertical"
# trailing_comma = "Always"
use_field_init_shorthand = true
## format_code_in_doc_comments = true
# # Warning: Unknown configuration option `format_doc_comments`
# format_doc_comments = true
hide_parse_errors = false
color = "Always"
unstable_features = true
#"edition = "2018"
#"version = "Two"
normalize_doc_attributes = true
space_after_colon = true
max_width = 80
trailing_semicolon = true
where_single_line = true
# width_heuristics = "Off"
empty_item_single_line = false
fn_params_layout = "Vertical"
force_multiline_blocks = true
format_code_in_doc_comments = true
match_arm_leading_pipes = "Always"
# match_arm_leading_pipes = "Preserve"
